- name: Setup Helm repos
  include_tasks: helm_repos.yaml

- name: Setup ingress controller
  include_tasks: ingress.yaml
  when: cm_cluster_type in ('KUBE_RKE', 'KUBE_K3S')

- name: Setup cert-manager
  include_tasks: certmanager.yaml

- name: Setup common storage providers
  include_tasks: storage.yaml
  when: rke_setup_storage_drivers

- name: Setup CloudMan
  include_tasks: cloudman.yaml
  when: cm_skip_cloudman is not defined or not (cm_skip_cloudman|bool)

- name: Configure private registries
  include_tasks: private_repos.yml
  when: config_private_repos

- name: Wait for CloudMan
  include_tasks: finish.yaml
