- name: Setup Rancher
  include_tasks: rancher.yaml
  when: cm_cluster_type == 'KUBE_RANCHER'
  tags:
    - rancher

- name: Setup Helm
  include_tasks: helm.yaml

- name: Setup common storage providers
  include_tasks: storage.yaml

- name: Setup cert-manager
  include_tasks: certmanager.yaml

- name: Setup Galaxy-CVMFS-CSI
  include_tasks: cvmfs.yaml

- name: Setup CloudMan
  include_tasks: cloudman.yaml
  when: cm_skip_cloudman is not defined or not (cm_skip_cloudman|bool)

- name: Setup Rancher Keycloak integration
  include_tasks: rancher_keycloak.yaml
  when: cm_cluster_type == 'KUBE_RANCHER'
  tags:
    - rancher

- name: Wait for CloudMan
  include_tasks: finish.yaml
